package rooms

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/AkagiYui/katrix/internal/crypto"
	"github.com/AkagiYui/katrix/internal/events"
	"github.com/AkagiYui/katrix/internal/ids"
	"github.com/AkagiYui/katrix/internal/roomver"
)

// Preset values for createRoom.
const (
	PresetPrivateChat        = "private_chat"
	PresetTrustedPrivateChat = "trusted_private_chat"
	PresetPublicChat         = "public_chat"
)

// CreateRequest is the parsed body of POST /createRoom.
type CreateRequest struct {
	CreationContent    json.RawMessage `json:"creation_content,omitempty"`
	Name               string          `json:"name,omitempty"`
	Topic              string          `json:"topic,omitempty"`
	RoomVersion        roomver.Version `json:"room_version,omitempty"`
	Preset             string          `json:"preset,omitempty"`
	RoomAliasName      string          `json:"room_alias_name,omitempty"`
	Visibility         string          `json:"visibility,omitempty"` // public|private
	Invite             []string        `json:"invite,omitempty"`
	IsDirect           *bool           `json:"is_direct,omitempty"`
	PowerLevelOverride json.RawMessage `json:"power_level_content_override,omitempty"`
}

// InitialPowerLevels builds the m.room.power_levels content for a new room,
// honouring the preset and an optional override.
func InitialPowerLevels(creator string, preset string, override json.RawMessage, privilegedCreator bool) (json.RawMessage, error) {
	pl := PowerLevels{
		UsersDefault:  0,
		EventsDefault: 0,
		StateDefault:  50,
		Ban:           50,
		Kick:          50,
		Redact:        50,
		Invite:        50,
		Events: map[string]int64{
			"m.room.name":               50,
			"m.room.power_levels":       100,
			"m.room.history_visibility": 100,
			"m.room.canonical_alias":    50,
			"m.room.avatar":             50,
			"m.room.topic":              50,
			"m.room.encryption":         100,
		},
	}
	// Room version 12 (MSC4289) raises the default m.room.tombstone requirement
	// to PL150 ("a new PL150 tier for tombstoning the room") so that regular
	// admins at PL100 cannot upgrade the room out from under the creator.
	pl.Events["m.room.tombstone"] = 100
	if privilegedCreator {
		pl.Events["m.room.tombstone"] = 150
	}
	// For rooms with privileged creators (v12+, MSC4239) the creator's power is
	// implicit and the creator is NOT listed in `users`; the map is emitted as
	// an empty object (never null). For older versions the creator is granted
	// 100 explicitly.
	if !privilegedCreator {
		pl.Users = map[string]int64{creator: 100}
	} else {
		pl.Users = map[string]int64{}
	}
	switch preset {
	case PresetPrivateChat, PresetTrustedPrivateChat:
		pl.Invite = 0
		pl.EventsDefault = 0
	case PresetPublicChat:
		pl.EventsDefault = 0
	}
	if len(override) > 0 {
		// Merge override fields over the defaults.
		var ov PowerLevels
		if err := json.Unmarshal(override, &ov); err != nil {
			return nil, fmt.Errorf("rooms: bad power_level_content_override: %w", err)
		}
		mergePowerLevels(&pl, &ov)
	}
	return json.Marshal(pl)
}

func mergePowerLevels(dst, src *PowerLevels) {
	if src.UsersDefault != 0 {
		dst.UsersDefault = src.UsersDefault
	}
	if src.EventsDefault != 0 {
		dst.EventsDefault = src.EventsDefault
	}
	if src.StateDefault != 0 {
		dst.StateDefault = src.StateDefault
	}
	if src.Ban != 0 {
		dst.Ban = src.Ban
	}
	if src.Kick != 0 {
		dst.Kick = src.Kick
	}
	if src.Redact != 0 {
		dst.Redact = src.Redact
	}
	if src.Invite != 0 {
		dst.Invite = src.Invite
	}
	for k, v := range src.Users {
		dst.Users[k] = v
	}
	for k, v := range src.Events {
		dst.Events[k] = v
	}
	for k, v := range src.Notifications {
		if dst.Notifications == nil {
			dst.Notifications = map[string]int64{}
		}
		dst.Notifications[k] = v
	}
}

// InitialJoinRules returns the m.room.join_rules content for a preset.
func InitialJoinRules(preset string) json.RawMessage {
	rule := JoinRuleInvite
	if preset == PresetPublicChat {
		rule = JoinRulePublic
	}
	b, _ := json.Marshal(map[string]string{"join_rule": rule})
	return b
}

// InitialHistoryVisibility returns the default m.room.history_visibility
// content ("shared" for public, "shared" for private -- spec default is shared;
// many clients use "shared" universally).
func InitialHistoryVisibility(preset string) json.RawMessage {
	vis := "shared"
	b, _ := json.Marshal(map[string]string{"history_visibility": vis})
	return b
}

// BuildInitialEvents constructs the initial set of state events for a new room:
// create, power_levels, join_rules, history_visibility, and a member(join) for
// the creator. It wires prev_events/auth_events and assigns depth. The first
// event (create) has no prev/auth events.
//
// roomID is pre-generated by the caller (for v12 it must be the create hash;
// callers using pre-v12 may pass a random id, for v12 they must re-derive --
// see BuildV12RoomID).
type InitialEventsResult struct {
	RoomID  string
	Events  []*events.Event
	Version roomver.Version
	Create  *events.Event
}

// BuildInitialEvents builds and signs the room's genesis state.
func BuildInitialEvents(
	roomID string,
	version roomver.Version,
	creator string,
	preset string,
	powerOverride json.RawMessage,
	creationContent json.RawMessage,
	isDirect bool,
	invitees []string,
	serverName string,
	key *crypto.SigningKey,
	now int64,
) (*InitialEventsResult, error) {
	rules, ok := roomver.Get(version)
	if !ok {
		return nil, fmt.Errorf("rooms: unsupported room version %q", version)
	}

	// For v12 (MSC4291), the room ID is derived from the create event's
	// reference hash, and the create event itself MUST NOT carry a room_id
	// field. We build the create with an empty room_id, derive the v12 room ID,
	// and use it for the remaining events. For earlier versions the caller-
	// supplied roomID is used directly in all events.
	v12RoomID := roomID
	if rules.RoomIDIsCreateHash {
		roomID = "" // create event omits room_id; the derived id is filled below.
	}

	// create content
	createContent := map[string]any{
		"creator":      creator,
		"room_version": string(version),
		"m.federate":   true,
	}
	if isDirect {
		createContent["m.federate"] = false // DMs typically non-federated
	}
	// Merge caller-supplied creation_content, which may carry custom keys and
	// override m.federate. Per the spec, room_version in creation_content is
	// ignored (the top-level room_version field controls the version); creator
	// is set by the server.
	if len(creationContent) > 0 {
		var extra map[string]json.RawMessage
		if json.Unmarshal(creationContent, &extra) == nil {
			for k, v := range extra {
				if k == "room_version" || k == "creator" {
					continue // reserved, server-controlled
				}
				// Decode the raw value into an any so the create event carries
				// the typed value rather than a raw JSON blob.
				var val any
				_ = json.Unmarshal(v, &val)
				createContent[k] = val
			}
		}
	}

	// additional_creators (MSC4289, room version 12): users granted the same
	// implicit power as the creator. The list must be an array of valid user
	// IDs; anything else is rejected. For a trusted_private_chat direct room the
	// invited users are implicitly added as additional creators.
	if rules.CreatorPrivileged {
		additional, err := validateAdditionalCreators(createContent["additional_creators"])
		if err != nil {
			return nil, err
		}
		if preset == PresetTrustedPrivateChat && isDirect {
			for _, inv := range invitees {
				if inv != "" && inv != creator && !containsUser(additional, inv) {
					additional = append(additional, inv)
				}
			}
		}
		if len(additional) > 0 {
			createContent["additional_creators"] = additional
		} else {
			delete(createContent, "additional_creators")
		}
	}
	createRaw, _ := json.Marshal(createContent)

	// Build create event (depth 0, no prev/auth). For v12 the room_id field is
	// omitted from the event JSON.
	createEv, err := buildAndSign(serverName, key, version, "m.room.create", "", creator, roomID, createRaw, now, 0, nil, nil)
	if err != nil {
		return nil, err
	}

	// For v12, derive the real room ID from the create event's reference hash
	// (room ID = "!" + url-safe base64 reference hash of the create event).
	if rules.RoomIDIsCreateHash {
		v12RoomID = BuildV12RoomID(version, createEv, serverName)
		roomID = v12RoomID
	}

	// power_levels
	plRaw, err := InitialPowerLevels(creator, preset, powerOverride, rules.CreatorPrivileged)
	if err != nil {
		return nil, err
	}

	// The auth_events for the non-create initial state events are:
	// [create, creator's member, power_levels, join_rules] per spec.
	// For room version 12 (MSC4291) the create event is omitted from every
	// event's auth_events — its presence is implied — so the creator-join
	// references nothing and the later events reference the prior initial
	// events only.
	creatorJoinRaw, _ := json.Marshal(map[string]any{
		"membership": MembershipJoin,
	})
	creatorJoinAuth := []string{createEv.EventID()}
	if rules.RoomIDIsCreateHash {
		creatorJoinAuth = nil
	}
	creatorJoin, err := buildAndSign(serverName, key, version, "m.room.member", creator, creator, roomID, creatorJoinRaw, now, 1,
		[]string{createEv.EventID()}, creatorJoinAuth)
	if err != nil {
		return nil, err
	}

	plAuth := []string{createEv.EventID(), creatorJoin.EventID()}
	if rules.RoomIDIsCreateHash {
		plAuth = []string{creatorJoin.EventID()}
	}
	plEv, err := buildAndSign(serverName, key, version, "m.room.power_levels", "", creator, roomID, plRaw, now, 2,
		[]string{creatorJoin.EventID()}, plAuth)
	if err != nil {
		return nil, err
	}

	jrEv, err := buildAndSign(serverName, key, version, "m.room.join_rules", "", creator, roomID, InitialJoinRules(preset), now, 3,
		[]string{plEv.EventID()}, append(plAuth, plEv.EventID()))
	if err != nil {
		return nil, err
	}

	hvEv, err := buildAndSign(serverName, key, version, "m.room.history_visibility", "", creator, roomID, InitialHistoryVisibility(preset), now, 4,
		[]string{jrEv.EventID()}, append(plAuth, plEv.EventID()))
	if err != nil {
		return nil, err
	}

	evs := []*events.Event{createEv, creatorJoin, plEv, jrEv, hvEv}
	return &InitialEventsResult{
		RoomID:  v12RoomID,
		Events:  evs,
		Version: version,
		Create:  createEv,
	}, nil
}

// validateAdditionalCreators checks that a parsed additional_creators value is
// an array of valid user ID strings (MSC4289). nil/absent yields nil.
func validateAdditionalCreators(v any) ([]string, error) {
	if v == nil {
		return nil, nil
	}
	arr, ok := v.([]any)
	if !ok {
		return nil, fmt.Errorf("rooms: additional_creators must be an array of user IDs")
	}
	out := make([]string, 0, len(arr))
	for _, e := range arr {
		s, ok := e.(string)
		if !ok || !isValidUserID(s) {
			return nil, fmt.Errorf("rooms: additional_creators must be an array of valid user IDs")
		}
		if !containsUser(out, s) {
			out = append(out, s)
		}
	}
	return out, nil
}

// isValidUserID reports whether s looks like a valid Matrix user ID
// (@localpart:server). The localpart allows the character set of the spec's
// user ID grammar; the server name allows the hostname grammar (letters, digits,
// dots and hyphens), so a domain with other punctuation is rejected.
func isValidUserID(s string) bool {
	if len(s) < 2 || s[0] != '@' {
		return false
	}
	colon := -1
	for i := 1; i < len(s); i++ {
		if s[i] == ':' {
			colon = i
			break
		}
	}
	if colon <= 1 || colon == len(s)-1 {
		return false
	}
	localpart := s[1:colon]
	domain := s[colon+1:]
	if domain == "" {
		return false
	}
	for _, c := range localpart {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
		case c == '.', c == '_', c == '=', c == '-', c == '/', c == '+':
		default:
			return false
		}
	}
	host := domain
	// A server name may carry a ":port" suffix (per the spec's server-name
	// grammar); validate the host and the port separately.
	if c := strings.LastIndex(host, ":"); c > 0 && c < len(host)-1 {
		for _, d := range host[c+1:] {
			if d < '0' || d > '9' {
				return false
			}
		}
		host = host[:c]
	}
	for _, c := range host {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
		case c == '.', c == '-':
		default:
			return false
		}
	}
	return true
}

// containsUser reports whether a user ID is present in a list.
func containsUser(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

// ValidatePrivilegedPowerOverride rejects a power_level_content_override whose
// `users` map lists the room creator or any additional creator (MSC4289, room
// version 12): their power is implicit and they must not appear in the users
// object. Returns nil when the override is absent or lists nobody privileged.
func ValidatePrivilegedPowerOverride(creator string, additional []string, override json.RawMessage) error {
	if len(override) == 0 || len(creator) == 0 {
		return nil
	}
	var ov struct {
		Users map[string]any `json:"users"`
	}
	if err := json.Unmarshal(override, &ov); err != nil || len(ov.Users) == 0 {
		return nil
	}
	if _, ok := ov.Users[creator]; ok {
		return fmt.Errorf("rooms: the room creator may not be listed in power_level_content_override users")
	}
	for _, ac := range additional {
		if _, ok := ov.Users[ac]; ok {
			return fmt.Errorf("rooms: additional creators may not be listed in power_level_content_override users")
		}
	}
	return nil
}

// buildAndSign is a thin wrapper over events.Builder for the genesis flow.
func buildAndSign(serverName string, key *crypto.SigningKey, version roomver.Version, eventType, stateKey, sender, roomID string, content json.RawMessage, ts int64, depth int64, prev, auth []string) (*events.Event, error) {
	rules, ok := roomver.Get(version)
	if !ok {
		return nil, fmt.Errorf("rooms: unsupported room version %q", version)
	}
	b := events.Builder{
		Type:           eventType,
		Sender:         sender,
		RoomID:         roomID,
		Content:        content,
		Depth:          depth,
		OriginServerTS: ts,
		PrevEvents:     prev,
		AuthEvents:     auth,
	}
	// All genesis events are state events. create/power_levels/join_rules/
	// history_visibility use state_key=""; member uses the target user id.
	// A nil StateKey would make it a non-state message, so always set it.
	sk := stateKey
	b.StateKey = &sk
	if rules.EventFormatV1 {
		// Room versions 1-2 use the legacy event format: explicit event_id
		// field and [id, hash] prev/auth references. Derive a stable event ID
		// localpart from the event type + depth so initial events are
		// deterministic across re-runs.
		localpart := ids.RandomTxnSuffix()
		if eventType == "m.room.create" {
			localpart = "create0"
		}
		return b.BuildLegacy(serverName, key, version, localpart)
	}
	return b.Build(serverName, key, version)
}

// BuildV12RoomID computes the v12 room ID as the url-safe base64 sha256 of the
// redacted create event's reference hash (MSC4291). Room version 12 drops the
// server-name suffix from room IDs entirely: the room ID is the create event's
// hash with the sigil swapped from $ to ! (e.g. "!<hash>"). For non-v12 it
// returns the supplied roomID unchanged.
func BuildV12RoomID(version roomver.Version, createEvent *events.Event, serverName string) string {
	rules, ok := roomver.Get(version)
	if !ok || !rules.RoomIDIsCreateHash {
		return createEvent.RoomID()
	}
	h, err := events.ReferenceHashBase64URL(createEvent.Raw(), rules)
	if err != nil {
		// Fall back to a random ID; this should not happen for a valid create.
		return "!" + ids.RandomLocalpart() + ":" + serverName
	}
	return "!" + h
}
