package rooms

import (
	"encoding/json"
	"fmt"

	"github.com/AkagiYui/katrix/internal/crypto"
	"github.com/AkagiYui/katrix/internal/events"
	"github.com/AkagiYui/katrix/internal/ids"
	"github.com/AkagiYui/katrix/internal/roomver"
)

// Preset values for createRoom.
const (
	PresetPrivateChat        = "private_chat"
	PresetTrustedPrivateChat = "trusted_private_chat"
	PresetPublicChat         = "public_chat"
)

// CreateRequest is the parsed body of POST /createRoom.
type CreateRequest struct {
	CreationContent    json.RawMessage `json:"creation_content,omitempty"`
	Name               string          `json:"name,omitempty"`
	Topic              string          `json:"topic,omitempty"`
	RoomVersion        roomver.Version `json:"room_version,omitempty"`
	Preset             string          `json:"preset,omitempty"`
	RoomAliasName      string          `json:"room_alias_name,omitempty"`
	Visibility         string          `json:"visibility,omitempty"` // public|private
	Invite             []string        `json:"invite,omitempty"`
	IsDirect           *bool           `json:"is_direct,omitempty"`
	PowerLevelOverride json.RawMessage `json:"power_level_content_override,omitempty"`
}

// InitialPowerLevels builds the m.room.power_levels content for a new room,
// honouring the preset and an optional override.
func InitialPowerLevels(creator string, preset string, override json.RawMessage) (json.RawMessage, error) {
	pl := PowerLevels{
		Users:         map[string]int64{creator: 100},
		UsersDefault:  0,
		EventsDefault: 0,
		StateDefault:  50,
		Ban:           50,
		Kick:          50,
		Redact:        50,
		Invite:        0,
		Events: map[string]int64{
			"m.room.name":               50,
			"m.room.power_levels":       100,
			"m.room.history_visibility": 100,
			"m.room.canonical_alias":    50,
			"m.room.avatar":             50,
			"m.room.topic":              50,
			"m.room.tombstone":          100,
			"m.room.encryption":         100,
		},
	}
	switch preset {
	case PresetPrivateChat, PresetTrustedPrivateChat:
		pl.Invite = 0
		pl.EventsDefault = 0
	case PresetPublicChat:
		pl.EventsDefault = 0
	}
	if len(override) > 0 {
		// Merge override fields over the defaults.
		var ov PowerLevels
		if err := json.Unmarshal(override, &ov); err != nil {
			return nil, fmt.Errorf("rooms: bad power_level_content_override: %w", err)
		}
		mergePowerLevels(&pl, &ov)
	}
	return json.Marshal(pl)
}

func mergePowerLevels(dst, src *PowerLevels) {
	if src.UsersDefault != 0 {
		dst.UsersDefault = src.UsersDefault
	}
	if src.EventsDefault != 0 {
		dst.EventsDefault = src.EventsDefault
	}
	if src.StateDefault != 0 {
		dst.StateDefault = src.StateDefault
	}
	if src.Ban != 0 {
		dst.Ban = src.Ban
	}
	if src.Kick != 0 {
		dst.Kick = src.Kick
	}
	if src.Redact != 0 {
		dst.Redact = src.Redact
	}
	if src.Invite != 0 {
		dst.Invite = src.Invite
	}
	for k, v := range src.Users {
		dst.Users[k] = v
	}
	for k, v := range src.Events {
		dst.Events[k] = v
	}
	for k, v := range src.Notifications {
		if dst.Notifications == nil {
			dst.Notifications = map[string]int64{}
		}
		dst.Notifications[k] = v
	}
}

// InitialJoinRules returns the m.room.join_rules content for a preset.
func InitialJoinRules(preset string) json.RawMessage {
	rule := JoinRuleInvite
	if preset == PresetPublicChat {
		rule = JoinRulePublic
	}
	b, _ := json.Marshal(map[string]string{"join_rule": rule})
	return b
}

// InitialHistoryVisibility returns the default m.room.history_visibility
// content ("shared" for public, "shared" for private -- spec default is shared;
// many clients use "shared" universally).
func InitialHistoryVisibility(preset string) json.RawMessage {
	vis := "shared"
	b, _ := json.Marshal(map[string]string{"history_visibility": vis})
	return b
}

// BuildInitialEvents constructs the initial set of state events for a new room:
// create, power_levels, join_rules, history_visibility, and a member(join) for
// the creator. It wires prev_events/auth_events and assigns depth. The first
// event (create) has no prev/auth events.
//
// roomID is pre-generated by the caller (for v12 it must be the create hash;
// callers using pre-v12 may pass a random id, for v12 they must re-derive --
// see BuildV12RoomID).
type InitialEventsResult struct {
	RoomID  string
	Events  []*events.Event
	Version roomver.Version
	Create  *events.Event
}

// BuildInitialEvents builds and signs the room's genesis state.
func BuildInitialEvents(
	roomID string,
	version roomver.Version,
	creator string,
	preset string,
	powerOverride json.RawMessage,
	creationContent json.RawMessage,
	isDirect bool,
	serverName string,
	key *crypto.SigningKey,
	now int64,
) (*InitialEventsResult, error) {
	rules, ok := roomver.Get(version)
	if !ok {
		return nil, fmt.Errorf("rooms: unsupported room version %q", version)
	}

	// For v12 (MSC4291), the room ID is derived from the create event's
	// reference hash, and the create event itself MUST NOT carry a room_id
	// field. We build the create with an empty room_id, derive the v12 room ID,
	// and use it for the remaining events. For earlier versions the caller-
	// supplied roomID is used directly in all events.
	v12RoomID := roomID
	if rules.RoomIDIsCreateHash {
		roomID = "" // create event omits room_id; the derived id is filled below.
	}

	// create content
	createContent := map[string]any{
		"creator":      creator,
		"room_version": string(version),
		"m.federate":   true,
	}
	if isDirect {
		createContent["m.federate"] = false // DMs typically non-federated
	}
	// Merge caller-supplied creation_content, which may carry custom keys and
	// override m.federate. Per the spec, room_version in creation_content is
	// ignored (the top-level room_version field controls the version); creator
	// is set by the server.
	if len(creationContent) > 0 {
		var extra map[string]json.RawMessage
		if json.Unmarshal(creationContent, &extra) == nil {
			for k, v := range extra {
				if k == "room_version" || k == "creator" {
					continue // reserved, server-controlled
				}
				// Decode the raw value into an any so the create event carries
				// the typed value rather than a raw JSON blob.
				var val any
				_ = json.Unmarshal(v, &val)
				createContent[k] = val
			}
		}
	}
	createRaw, _ := json.Marshal(createContent)

	// Build create event (depth 0, no prev/auth). For v12 the room_id field is
	// omitted from the event JSON.
	createEv, err := buildAndSign(serverName, key, version, "m.room.create", "", creator, roomID, createRaw, now, 0, nil, nil)
	if err != nil {
		return nil, err
	}

	// For v12, derive the real room ID from the create event's reference hash
	// (room ID = "!" + url-safe base64 reference hash of the create event).
	if rules.RoomIDIsCreateHash {
		v12RoomID = BuildV12RoomID(version, createEv, serverName)
		roomID = v12RoomID
	}

	// power_levels
	plRaw, err := InitialPowerLevels(creator, preset, powerOverride)
	if err != nil {
		return nil, err
	}

	// The auth_events for the non-create initial state events are:
	// [create, creator's member, power_levels, join_rules] per spec.
	// For the initial creator-join member event, auth = [create, power_levels].
	creatorJoinRaw, _ := json.Marshal(map[string]any{
		"membership": MembershipJoin,
	})
	creatorJoin, err := buildAndSign(serverName, key, version, "m.room.member", creator, creator, roomID, creatorJoinRaw, now, 1,
		[]string{createEv.EventID()}, []string{createEv.EventID()})
	if err != nil {
		return nil, err
	}

	plEv, err := buildAndSign(serverName, key, version, "m.room.power_levels", "", creator, roomID, plRaw, now, 2,
		[]string{creatorJoin.EventID()}, []string{createEv.EventID(), creatorJoin.EventID()})
	if err != nil {
		return nil, err
	}

	jrEv, err := buildAndSign(serverName, key, version, "m.room.join_rules", "", creator, roomID, InitialJoinRules(preset), now, 3,
		[]string{plEv.EventID()}, []string{createEv.EventID(), creatorJoin.EventID(), plEv.EventID()})
	if err != nil {
		return nil, err
	}

	hvEv, err := buildAndSign(serverName, key, version, "m.room.history_visibility", "", creator, roomID, InitialHistoryVisibility(preset), now, 4,
		[]string{jrEv.EventID()}, []string{createEv.EventID(), creatorJoin.EventID(), plEv.EventID()})
	if err != nil {
		return nil, err
	}

	evs := []*events.Event{createEv, creatorJoin, plEv, jrEv, hvEv}
	return &InitialEventsResult{
		RoomID:  v12RoomID,
		Events:  evs,
		Version: version,
		Create:  createEv,
	}, nil
}

// buildAndSign is a thin wrapper over events.Builder for the genesis flow.
func buildAndSign(serverName string, key *crypto.SigningKey, version roomver.Version, eventType, stateKey, sender, roomID string, content json.RawMessage, ts int64, depth int64, prev, auth []string) (*events.Event, error) {
	rules, ok := roomver.Get(version)
	if !ok {
		return nil, fmt.Errorf("rooms: unsupported room version %q", version)
	}
	b := events.Builder{
		Type:           eventType,
		Sender:         sender,
		RoomID:         roomID,
		Content:        content,
		Depth:          depth,
		OriginServerTS: ts,
		PrevEvents:     prev,
		AuthEvents:     auth,
	}
	// All genesis events are state events. create/power_levels/join_rules/
	// history_visibility use state_key=""; member uses the target user id.
	// A nil StateKey would make it a non-state message, so always set it.
	sk := stateKey
	b.StateKey = &sk
	if rules.EventFormatV1 {
		// Room versions 1-2 use the legacy event format: explicit event_id
		// field and [id, hash] prev/auth references. Derive a stable event ID
		// localpart from the event type + depth so initial events are
		// deterministic across re-runs.
		localpart := ids.RandomTxnSuffix()
		if eventType == "m.room.create" {
			localpart = "create0"
		}
		return b.BuildLegacy(serverName, key, version, localpart)
	}
	return b.Build(serverName, key, version)
}

// BuildV12RoomID computes the v12 room ID as the url-safe base64 sha256 of the
// redacted create event's reference hash (MSC4291), suffixed with the server
// name. For non-v12 it returns the supplied roomID unchanged.
func BuildV12RoomID(version roomver.Version, createEvent *events.Event, serverName string) string {
	rules, ok := roomver.Get(version)
	if !ok || !rules.RoomIDIsCreateHash {
		return createEvent.RoomID()
	}
	h, err := events.ReferenceHashBase64URL(createEvent.Raw(), rules)
	if err != nil {
		// Fall back to a random ID; this should not happen for a valid create.
		return "!" + ids.RandomLocalpart() + ":" + serverName
	}
	return "!" + h + ":" + serverName
}
